version = "1.0"

################################################################################
#### ABOUT PANELS
################################################################################

[main]

    [main.network]
        [main.network.iface]
        ask = "Network interface at boot"
        type = "string"
        help = "Interface on which dropbear (the SSH server) should listen when booting"
        bind = "null"

        [main.network.ip]
        ask  = "Static IP address at boot"
        type = "string"
        help = "IP address that should be set for dropbear."
        pattern.regexp = '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
        pattern.error = "Please fill an IP v4 address"
        bind = "null"

        [main.network.mask]
        ask  = "Mask at boot"
        type = "string"
        help = "Mask that should be set for dropbear."
        pattern.regexp = '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
        pattern.error = "Please fill an IP v4 address"
        bind = "null"

        [main.network.gateway]
        ask  = "Gateway at boot"
        type = "string"
        help = "Gateway that should be set for dropbear."
        pattern.regexp = '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
        pattern.error = "Please fill an IP v4 address"
        bind = "null"

    [main.security]
        [main.security.authorized_keys]
        ask  = "Authorized SSH keys at boot"
        type = "text"
        optional = true
        bind = "/etc/dropbear/initramfs/authorized_keys"
