#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cryptroot-unlock"
name = "Cryptroot unlock"
description.en = "Unlock through SSH your partitions encrypted with LUKS"
description.fr = "Déverrouillez vos partitions LUKS chiffrées via SSH"

version = "1.0~ynh2"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0-or-later"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "5M"
ram.runtime = "5M"

[install]
    [install.iface]
    type = "string"
    ask.en = "Select the network interface that dropbear (the SSH server) will listen on during boot"
    ask.fr = "Sélectionnez l'interface réseau sur laquelle dropbear (le serveur SSH) écoutera au démarrage"
    help.en = "The IP address, mask, and gateway will be automatically deduced during the app installation"
    help.fr = "L'adresse IP, le masque et la passerelle seront déduis automatiquement durant l'installation de l'application"

    [install.user_reuse_authorized_keys]
    type = "user"
    optional = true
    ask.en = "(Optional) Select a user whose authorized SSH keys will be copied for dropbear during the installation"
    ask.fr = "(Optionnel) Sélectionnez un utilisateur dont les clés SSH autorisées seront copiées pour dropbear durant l'installation"
    help.en = "These SSH keys will be allowed to connect during the system boot and to unlock your partitions"
    help.fr = "Ces clés SSH seront autorisées à se connecter durant le démarrage du système pour déverrouiller vos partitions"

    [install.authorized_keys]
    type = "text"
    optional = true
    ask.en = "(Optional) Add extra SSH public keys allowed to unlock your partitions"
    ask.fr = "(Optionnel) Ajoutez des clés SSH publiques supplémentaires autorisées à déverrouiller vos partitions"
    help.en = "These SSH keys will be allowed to connect during the system boot and to unlock your partitions"
    help.fr = "Ces clés SSH seront autorisées à se connecter durant le démarrage du système pour déverrouiller vos partitions"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those


    [resources.ports]
    main.default = 2222

    [resources.apt]
    packages = "busybox dropbear-initramfs initramfs-tools"
