#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cryptroot-unlock"
name = "cryptroot unlock"
description.en = "Unlock through SSH your partitions encrypted with LUKS"
description.fr = "Déverrouillez via SSH vos partitions chiffrées via LUKS"

version = "1.0~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "AGPL-3.0-or-later"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "5M"
ram.runtime = "5M"

[install]
    [install.iface]
    type = "string"
    ask.en = "Select the network interface which dropbear (the SSH server) will allow you to connect. The IP address, mask, gateway, will be detected and defined as is for dropbear."
    ask.fr = "Sélectionnez l'interface réseau pour laquelle dropbear (le serveur SSH) autorisera les connexions. L'adresse IP, le masque et la passerelle seront détectés et défini tel quel pour dropbear."

    [install.user_reuse_authorized_keys]
    type = "user"
    optional = true
    ask.en = "Select a user you would like to copy the authorized SSH keys to unlock your paritions (optional)"
    ask.fr = "Choisissez un utilisateur pour qui vous souhaitez réutiliser les clé SSH autorisées à déverrouiller vos partitions (optionnel)"

    [install.authorized_keys]
    type = "text"
    optional = true
    ask.en = "Additional authorized SSH keys you would like to allow unlocking your paritions (optional)"
    ask.fr = "Clés SSH supplémentaires à autoriser à se connecter pour déverrouiller les partitions (optionnel)"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those


    [resources.ports]
    main.default = 2222

    [resources.apt]
    packages = "dropbear-initramfs initramfs-tools"
