#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE DATA DIR
#=================================================


#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Check whether the backup is meaningful
if [ ! -s "$DROPBEAR_INITRAMFS_DIR/authorized_keys" ]; then 
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file does not exist or is empty, aborting."
fi
if ! validate_authorized_keys < "$DROPBEAR_INITRAMFS_DIR/authorized_keys"; then
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file already exists but contains invalid keys, aborting."
fi

# Backup the PHP-FPM configuration
ynh_backup "$INITRAMFS_CONF"
ynh_backup "$DROPBEAR_INITRAMFS_DIR"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
