#!/bin/bash
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__iface() {
  ynh_app_setting_get --key=iface
}

get__ip() {
  ynh_app_setting_get --key=ip
}

get__mask() {
  ynh_app_setting_get --key=mask
}

get__gateway() {
  ynh_app_setting_get --key=gateway
}

# get__enable_dropbear() {
#   if systemctl is-active dropbear; then
#     echo 1
#   else
#     echo 0
#   fi
# }

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

validate__iface() {
  if ip -j a | jq -r ".[].ifname" | grep -Fxq "$iface"; then
    echo "This does not seem to be a network interface recognized by your server"
  fi
}


#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__iface() {
    ynh_app_setting_set --key=iface --value="$iface"
    configure_initramfs
}

set__ip() {
    ynh_app_setting_set --key=ip --value="$ip"
    configure_initramfs
}

set__mask() {
    ynh_app_setting_set --key=mask --value="$mask"
    configure_initramfs
}

set__gateway() {
    ynh_app_setting_set --key=gateway --value="$gateway"
    configure_initramfs
}

# set__enable_dropbear() {
#   if [ "$enable_dropbear" -eq "1" ]; then
#     systemctl enable dropbear
#   else
#     systemctl disable dropbear
#   fi
# }

#=================================================
ynh_app_config_run "$1"
