#!/bin/bash
# In simple cases, you don't need a config script.

# With a simple config_panel.toml, you can write in the app settings, in the
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__iface() {
  ynh_app_setting_get --key=iface
}

get__ip() {
  ynh_app_setting_get --key=ip
}

get__mask() {
  ynh_app_setting_get --key=mask
}

get__gateway() {
  ynh_app_setting_get --key=mask
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================
set__iface() {
    ynh_app_setting_set --key=iface --value="$iface"
    configure_initramfs
}

set__ip() {
    ynh_app_setting_set --key=ip --value="$ip"
    configure_initramfs
}

set__mask() {
    ynh_app_setting_set --key=mask --value="$mask"
    configure_initramfs
}

set__gateway() {
    ynh_app_setting_set --key=gateway --value="$gateway"
    configure_initramfs
}

#=================================================
ynh_app_config_run "$1"
