#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if [ ! -f "/etc/crypttab" ] && [ "${container:-}" != "lxc" ]; then
    ynh_die "Your system is probably not encrypted, abort"
fi

# FIXME: Also support IPv6
# https://wiki.faimaison.net/doku.php?id=debian-fde-dropbear&s%5B%5D=crypt&s%5B%5D=unlock#et_en_ipv6
# https://lists.debian.org/debian-ipv6/2024/03/msg00002.html

IFS='|' read ip cidr_mask < <(ip -j -4 a show dev "$iface" | jq -r '.[0].addr_info[0] | [.local,.prefixlen] | join("|")')
gateway=$(ip -j route | jq -r '.[] | select(.dst == "default") | .gateway' | head -n 1)
mask=$(cidr_to_netmask "$cidr_mask")

ynh_app_setting_set --key=ip --value=$ip
ynh_app_setting_set --key=mask --value=$mask
ynh_app_setting_set --key=gateway --value=$gateway

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# Bail out if no install questions regarding SSH keys have been answered 
if [ -z "${user_reuse_authorized_keys:-}" ] && [ -z "${authorized_keys:-}" ]; then
    ynh_die "You must set an SSH key (reusing an existing one and/or adding new ones) during the install questions in order to be granted remote access to your server after reboot."
fi

configure_initramfs

touch $DROPBEAR_INITRAMFS_DIR/authorized_keys

if [ -n "${user_reuse_authorized_keys:-}" ]; then
    user_home="$(getent passwd $user_reuse_authorized_keys | cut -d : -f 6)"
    if [ -s "$user_home/.ssh/authorized_keys" ]; then
        # The file exists and is not empty
        cp "$user_home/.ssh/authorized_keys" $DROPBEAR_INITRAMFS_DIR/authorized_keys
    elif [ -z "${authorized_keys:-}" ]; then
        # Selected user does not have a valid authorized_key file and no other key was set in install questions. 
        ynh_die "The selected user doesn't have any valid key to use. You must set an SSH key (reusing an existing one and/or adding new ones) during the install questions in order to be granted remote access to your server after reboot."
    fi
fi

if [ -n "${authorized_keys:-}" ]; then
    echo "" >> "$DROPBEAR_INITRAMFS_DIR/authorized_keys"
    echo "$authorized_keys" >> "$DROPBEAR_INITRAMFS_DIR/authorized_keys"
fi

if [ -f "$DROPBEAR_INITRAMFS_DIR/authorized_keys" ]; then
    chmod 600 "$DROPBEAR_INITRAMFS_DIR/authorized_keys"
fi

add_dropbear_options

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

ynh_script_progression "Installation of $app completed"
