#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

if [ ! -f "/etc/crypttab" ] && [ "${container:-}" != "lxc" ]; then
  ynh_die "Your system is probably not encrypted, abort"
fi

# FIXME: Also support IPv6
# https://wiki.faimaison.net/doku.php?id=debian-fde-dropbear&s%5B%5D=crypt&s%5B%5D=unlock#et_en_ipv6
# https://lists.debian.org/debian-ipv6/2024/03/msg00002.html

IFS='|' read ip cidr_mask < <(ip -j -4 a show dev "$iface" | jq -r '.[0].addr_info[0] | [.local,.prefixlen] | join("|")')
gateway=$(ip -j route | jq -r '.[] | select(.dst == "default") | .gateway' | head -n 1)
mask=$(cidr_to_netmask "$cidr_mask")

ynh_app_setting_set --key=ip --value=$ip
ynh_app_setting_set --key=mask --value=$mask
ynh_app_setting_set --key=gateway --value=$gateway

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

configure_initramfs


if [ -n "${user_reuse_authorized_keys:-}" ]; then
  user_home="$(getent passwd $user_reuse_authorized_keys | cut -d : -f 6)"
  if [ -f "$user_home/.ssh/authorized_keys" ]; then
    cp "$user_home/.ssh/authorized_keys" $DROPBEAR_INITRAMFS_DIR/authorized_keys
  fi
fi

if [ -n "${authorized_keys:-}" ]; then
  echo "" >> $DROPBEAR_INITRAMFS_DIR/authorized_keys
  echo "$authorized_keys" >> $DROPBEAR_INITRAMFS_DIR/authorized_keys
fi

if [ -f "$DROPBEAR_INITRAMFS_DIR/authorized_keys" ]; then
  chmod 600 "$DROPBEAR_INITRAMFS_DIR/authorized_keys"
fi

add_dropbear_options

# Don't enable dropbear unless told.
# if [ "${enable_dropbear:-}" != "true" ]; then
#   systemctl disable dropbear
# fi

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

ynh_script_progression "Installation of $app completed"
