#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

unconfigure_initramfs

ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
