#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE CONFIG
#=================================================
ynh_script_progression "Restoring the configuration..."

ynh_restore "$INITRAMFS_CONF"
chown "root:root" "$INITRAMFS_CONF"
chmod 600 "$INITRAMFS_CONF"

ynh_restore "$DROPBEAR_INITRAMFS_DIR"
chown -R "root:root" "$DROPBEAR_INITRAMFS_DIR"
chmod -R 600 "$DROPBEAR_INITRAMFS_DIR"

# Make sure the backup to restore includes at least one valid SSH key
if [ ! -s "$DROPBEAR_INITRAMFS_DIR/authorized_keys" ]; then 
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file does not exist or is empty, aborting."
fi
if ! validate_authorized_keys < "$DROPBEAR_INITRAMFS_DIR/authorized_keys"; then
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file already exists but contains invalid keys, aborting."
fi

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
