#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

configure_initramfs

if [ -n "${reuse_authorized_keys:-}" ] && [ -f "$reuse_authorized_keys/.ssh/authorized_keys" ]; then
  cp "$reuse_authorized_keys/.ssh/authorized_keys" $DROPBEAR_INITRAMFS_DIR/authorized_keys
fi

if [ -n "$authorized_keys" ]; then
  echo "" >> $DROPBEAR_INITRAMFS_DIR/authorized_keys
  echo "$authorized_keys" >> $DROPBEAR_INITRAMFS_DIR/authorized_keys
fi

add_dropbear_options

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
