#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

if [ ! -s "$DROPBEAR_INITRAMFS_DIR/authorized_keys" ]; then 
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file does not exist or is empty, aborting."
fi
if ! validate_authorized_keys < "$DROPBEAR_INITRAMFS_DIR/authorized_keys"; then
    ynh_die "The $DROPBEAR_INITRAMFS_DIR/authorized_keys file already exists but contains invalid keys, aborting."
fi

add_dropbear_options

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
