#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

touch $DROPBEAR_INITRAMFS_DIR/authorized_keys

configure_initramfs

add_dropbear_options

#=================================================
# INITRAMFS
#=================================================
ynh_script_progression "Rebuilding initramfs"
update-initramfs -k all -u

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
